openapi: 3.0.3
info:
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Hyperledger Cactus Plugin - HTLC-ETH Besu
  version: 3.0.1
servers:
- url: /
paths:
  /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/new-contract:
    post:
      operationId: newContractV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewContractObj"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvokeContractV1Response"
          description: OK
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/new-contract
  /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/withdraw:
    post:
      operationId: withdrawV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WithdrawReq"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvokeContractV1Response"
          description: OK
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/withdraw
  /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/refund:
    post:
      operationId: refundV1
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefundReq"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvokeContractV1Response"
          description: OK
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/refund
  /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/get-status:
    post:
      operationId: getStatusV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetStatusRequest"
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  format: uint256
                  type: integer
                type: array
          description: Array of status
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/get-status
  /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/get-single-status:
    post:
      operationId: getSingleStatusV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetSingleStatusRequest"
      responses:
        "200":
          content:
            application/json:
              schema:
                format: uint256
                type: integer
          description: Status
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/get-single-status
  /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/initialize:
    post:
      operationId: initializeV1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InitializeRequest"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunTransactionResponse"
          description: OK
      x-hyperledger-cacti:
        http:
          verbLowerCase: post
          path: /api/v1/plugins/@hyperledger-cacti/cactus-plugin-htlc-eth-besu/initialize
components:
  responses:
    GetStatusResponse:
      content:
        application/json:
          schema:
            items:
              format: uint256
              type: integer
            type: array
      description: Array of status
    GetSingleStatusResponse:
      content:
        application/json:
          schema:
            format: uint256
            type: integer
      description: Status
  schemas:
    NewContractObj:
      additionalProperties: false
      example:
        contractAddress: contractAddress
        inputAmount: 0.8008281904610115
        outputAmount: 6.027456183070403
        expiration: 1.4658129805029452
        hashLock: hashLock
        receiver: receiver
        outputNetwork: outputNetwork
        outputAddress: outputAddress
        connectorId: connectorId
        web3SigningCredential:
          type: CACTUS_KEYCHAIN_REF
        keychainId: keychainId
        gas: NewContractObj_gas
      properties:
        contractAddress:
          description: Contract address
          nullable: false
          type: string
        inputAmount:
          type: number
        outputAmount:
          type: number
        expiration:
          type: number
        hashLock:
          type: string
        receiver:
          type: string
        outputNetwork:
          nullable: false
          type: string
        outputAddress:
          nullable: false
          type: string
        connectorId:
          description: connectorId for the connector besu plugin
          nullable: false
          type: string
        web3SigningCredential:
          $ref: "#/components/schemas/Web3SigningCredential"
        keychainId:
          description: keychainId for the keychian plugin
          nullable: false
          type: string
        gas:
          $ref: "#/components/schemas/NewContractObj_gas"
      required:
      - connectorId
      - contractAddress
      - expiration
      - hashLock
      - keychainId
      - outputAddress
      - outputAmount
      - outputNetwork
      - web3SigningCredential
      type: object
    RefundReq:
      additionalProperties: false
      example:
        id: id
        web3SigningCredential:
          type: CACTUS_KEYCHAIN_REF
        connectorId: connectorId
        keychainId: keychainId
        gas: NewContractObj_gas
      properties:
        id:
          description: Contract htlc id for refund
          nullable: false
          type: string
        web3SigningCredential:
          $ref: "#/components/schemas/Web3SigningCredential"
        connectorId:
          description: connectorId for the connector besu plugin
          nullable: false
          type: string
        keychainId:
          description: keychainId for the keychain plugin
          nullable: false
          type: string
        gas:
          $ref: "#/components/schemas/NewContractObj_gas"
      required:
      - connectorId
      - id
      - keychainId
      - web3SigningCredential
      type: object
    WithdrawReq:
      additionalProperties: false
      example:
        id: id
        secret: secret
        web3SigningCredential:
          type: CACTUS_KEYCHAIN_REF
        connectorId: connectorId
        keychainId: keychainId
        gas: NewContractObj_gas
      properties:
        id:
          description: Contract locked id
          nullable: false
          type: string
        secret:
          description: Secret need to unlock the contract
          nullable: false
          type: string
        web3SigningCredential:
          $ref: "#/components/schemas/Web3SigningCredential"
        connectorId:
          description: connectorId for the connector besu plugin
          nullable: false
          type: string
        keychainId:
          description: keychainId for the keychain plugin
          nullable: false
          type: string
        gas:
          $ref: "#/components/schemas/NewContractObj_gas"
      required:
      - connectorId
      - id
      - keychainId
      - secret
      - web3SigningCredential
      type: object
    InitializeRequest:
      additionalProperties: false
      example:
        connectorId: connectorId
        keychainId: keychainId
        constructorArgs:
        - ""
        - ""
        web3SigningCredential:
          type: CACTUS_KEYCHAIN_REF
        gas: 0.8008281904610115
      properties:
        connectorId:
          description: connectorId for the connector besu plugin
          nullable: false
          type: string
        keychainId:
          description: keychainId for the keychain plugin
          nullable: false
          type: string
        constructorArgs:
          default: []
          items: {}
          type: array
        web3SigningCredential:
          $ref: "#/components/schemas/Web3SigningCredential"
        gas:
          type: number
      required:
      - connectorId
      - constructorArgs
      - keychainId
      - web3SigningCredential
      type: object
    GetStatusRequest:
      additionalProperties: false
      description: Defines the parameters for retrieving the status of the HTLC swap.
      example:
        ids:
        - ids
        - ids
        web3SigningCredential:
          type: CACTUS_KEYCHAIN_REF
        connectorId: connectorId
        keychainId: keychainId
      properties:
        ids:
          items:
            type: string
          type: array
        web3SigningCredential:
          $ref: "#/components/schemas/Web3SigningCredential"
        connectorId:
          type: string
        keychainId:
          type: string
      required:
      - connectorId
      - ids
      - keychainId
      - web3SigningCredential
      type: object
    GetSingleStatusRequest:
      additionalProperties: false
      description: Defines the parameters for retrieving the single status of the
        HTLC swap.
      example:
        id: id
        web3SigningCredential:
          type: CACTUS_KEYCHAIN_REF
        connectorId: connectorId
        keychainId: keychainId
      properties:
        id:
          type: string
        web3SigningCredential:
          $ref: "#/components/schemas/Web3SigningCredential"
        connectorId:
          type: string
        keychainId:
          type: string
      required:
      - connectorId
      - id
      - keychainId
      - web3SigningCredential
      type: object
    Web3SigningCredentialType:
      enum:
      - CACTUS_KEYCHAIN_REF
      - GETH_KEYCHAIN_PASSWORD
      - PRIVATE_KEY_HEX
      - NONE
      type: string
    Web3SigningCredentialCactusKeychainRef:
      properties:
        type:
          $ref: "#/components/schemas/Web3SigningCredentialType"
        ethAccount:
          description: The ethereum account (public key) that the credential  belongs
            to. Basically the username in the traditional  terminology of authentication.
          maxLength: 64
          minLength: 64
          nullable: false
          type: string
        keychainEntryKey:
          description: The key to use when looking up the the keychain entry holding
            the secret pointed to by the  keychainEntryKey parameter.
          maxLength: 1024
          minLength: 0
          type: string
        keychainId:
          description: The keychain ID to use when looking up the the keychain plugin
            instance that will be used to retrieve the secret pointed to by the keychainEntryKey
            parameter.
          maxLength: 1024
          minLength: 0
          type: string
      required:
      - ethAccount
      - keychainEntryKey
      - keychainId
      - type
      type: object
    Web3SigningCredentialPrivateKeyHex:
      properties:
        type:
          $ref: "#/components/schemas/Web3SigningCredentialType"
        ethAccount:
          description: The ethereum account (public key) that the credential belongs
            to. Basically the username in the traditional terminology of authentication.
          maxLength: 64
          minLength: 64
          nullable: false
          type: string
        secret:
          description: The HEX encoded private key of an eth account.
          maxLength: 65535
          minLength: 0
          type: string
      required:
      - ethAccount
      - secret
      - type
      type: object
    Web3SigningCredentialNone:
      description: Using this denotes that there is no signing required because the
        transaction is pre-signed.
      properties:
        type:
          $ref: "#/components/schemas/Web3SigningCredentialType"
      required:
      - type
      type: object
    Web3SigningCredential:
      discriminator:
        propertyName: type
      example:
        type: CACTUS_KEYCHAIN_REF
      oneOf:
      - $ref: "#/components/schemas/Web3SigningCredentialCactusKeychainRef"
      - $ref: "#/components/schemas/Web3SigningCredentialPrivateKeyHex"
      - $ref: "#/components/schemas/Web3SigningCredentialNone"
      properties:
        type:
          $ref: "#/components/schemas/Web3SigningCredentialType"
      required:
      - type
      type: object
    Web3TransactionReceipt:
      additionalProperties: true
      example:
        status: true
        transactionHash: transactionHash
        transactionIndex: 0.8008281904610115
        blockHash: blockHash
        blockNumber: 6.027456183070403
        gasUsed: 1.4658129805029452
        contractAddress: contractAddress
        from: from
        to: to
      properties:
        status:
          nullable: false
          type: boolean
        transactionHash:
          maxLength: 66
          minLength: 66
          pattern: "^0x([A-Fa-f0-9]{64})$"
          type: string
        transactionIndex:
          nullable: false
          type: number
        blockHash:
          maxLength: 66
          minLength: 66
          pattern: "^0x([A-Fa-f0-9]{64})$"
          type: string
        blockNumber:
          nullable: false
          type: number
        gasUsed:
          nullable: false
          type: number
        contractAddress:
          nullable: true
          type: string
        from:
          nullable: false
          type: string
        to:
          nullable: false
          type: string
      required:
      - blockHash
      - blockNumber
      - from
      - gasUsed
      - status
      - to
      - transactionHash
      - transactionIndex
      type: object
    InvokeContractV1Response:
      example:
        transactionReceipt:
          status: true
          transactionHash: transactionHash
          transactionIndex: 0.8008281904610115
          blockHash: blockHash
          blockNumber: 6.027456183070403
          gasUsed: 1.4658129805029452
          contractAddress: contractAddress
          from: from
          to: to
        callOutput: ""
        success: true
      properties:
        transactionReceipt:
          $ref: "#/components/schemas/Web3TransactionReceipt"
        callOutput: {}
        success:
          nullable: false
          type: boolean
      required:
      - success
      type: object
    RunTransactionResponse:
      example:
        transactionReceipt:
          status: true
          transactionHash: transactionHash
          transactionIndex: 0.8008281904610115
          blockHash: blockHash
          blockNumber: 6.027456183070403
          gasUsed: 1.4658129805029452
          contractAddress: contractAddress
          from: from
          to: to
      properties:
        transactionReceipt:
          $ref: "#/components/schemas/Web3TransactionReceipt"
      required:
      - transactionReceipt
      type: object
    NewContractObj_gas:
      oneOf:
      - type: string
      - type: number
